### PR TITLE
PanZoomWithCover: Fix Hydration Error

### PR DESCRIPTION
**Pull request by HighLiuk**
This PR fixes the following [React Hydration Error](https://nextjs.org/docs/messages/react-hydration-error) caused in SSR frameworks like Next.js.
Related errors:
- [text content does not match server-rendered html](https://www.netlify.com/blog/fix-next-js-react-hydration-error/)
- [hydration failed because the initial ui does not match what was rendered on the server](https://stackoverflow.com/questions/71706064/react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-render)

This was caused mainly by two things:

- ### Single quotes not escaped with `dangerouslySetInnerHTML`
Screenshot 2022-12-04 at 22 35 44

- ### WITH_COVER_ID not correctly synced between Client and Server
Screenshot 2022-12-04 at 22 40 43

@sasza2 can you review it and merge it if you think it's Ok? 🙂

### CODE REVIEW

**Comment by sasza2** [comment]
Hi, thanks a lot for catching it and creating PR. the whole idea with id++ was to let possible having multiple `<PanzoomWithCover />` components on one screen. did you check this case?

**Comment by HighLiuk** [comment]
Hi @sasza2, I guess you can have more of them and style them differently by assigning them different classnames

**Comment by sasza2** [comment]
yes, but after your changes if someone doesnt pass className prop it would probably broke hehe (every components would have got same background). I will check it live tommorow

**Comment by HighLiuk** [comment]
Oh yeah I got it. We could encode the url though, or have some trick like that

**Comment by HighLiuk** [comment]
Oh yeah I got it. Let me think about a slightly different approach then...

**Comment by HighLiuk** [comment]
@sasza2 I think this solution is the easiest, here you can see that this way it does not make any conflict between components.
What do you think about this approach?

Screenshot 2022-12-05 at 00 21 21

**Review by sasza2 — APPROVED** [review]
it's perfect now. thank you

**Comment by HighLiuk** [comment]
Thank you @sasza2, I'm really happy to have contributed.
This is my first PR accepted on an open source project 🙂 and I hope it won't be the last one!

**Comment by sasza2** [comment]
I hope that too! Wish you that this is the beginning of a wonderful journey hehe

**Pull request merged**
